name: wirepas-gateway-ben # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A gateway for Wirepas Mesh nodes # 79 char long summary
description: Connect your Wirepas Mesh Network to the internet.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

hooks:
  connect-plug-serial-port:
    plugs: [serial-port]


apps:
  sinkService0:    
    command: sink-service.sh -i 0
    slots: [wirepas-sink-0]
    plugs: [serial-port]
    daemon: simple
    restart-condition: always
    restart-delay: 5s

  wm-gw:
    command: python3.7 -u $SNAP/bin/wm-gw
    plugs:
     - home
     - network
    environment:
      PYTHONPATH: $PYTHONPATH:$SNAP/lib/python3.7/site-packages/:$SNAP/lib/python3.7/site-packages/PyGObject-3.36.1-py3.7-linux-x86_64.egg/:$SNAP/lib/python3.7/site-packages/PyGObject-3.36.1-py3.7-linux-armv7l.egg:$SNAP/lib/python3.7/site-packages/PyGObject-3.36.1-py3.7-linux-aarch64.egg


parts:
  sink-service:
    plugin: nil
    source-type: git
    source: https://github.com/wirepas/gateway.git
    source-tag: v1.3.0
    source-subdir: gateway/sink_service
    override-pull: |
      snapcraftctl pull 
      git clone https://github.com/wirepas/c-mesh-api.git
      mv c-mesh-api/ sink_service/c-mesh-api
    build-packages:
      - gcc
      - make
    override-build: |
      cd sink_service/
      make
      cp -r build/sinkService ${SNAPCRAFT_PART_INSTALL}
  transport:
    plugin: nil
    stage-packages:
      - python3.7
      - python3-gi
      - libglib2.0-0
      - libgirepository-1.0-1
      - libgirepository1.0-dev
      - libffi6
    source: https://github.com/protocolbuffers/protobuf/releases/download/v3.9.0/protobuf-python-3.9.0.tar.gz
    override-build: |
      ./configure
      snapcraftctl build
      ldconfig
      /bin/bash -c "/usr/bin/python3.7 <(wget -q -O - https://bootstrap.pypa.io/get-pip.py) --prefix $SNAPCRAFT_PART_INSTALL --no-compile"
      cp -r /usr/lib/python3.7/distutils $SNAPCRAFT_PART_INSTALL/lib/python3.7/site-packages/distutils
      find $SNAPCRAFT_PART_INSTALL -type d -name __pycache__ -print0 | xargs -0 rm -rf
      rm -rf venv
      /usr/bin/python3.7 -m venv venv
      wget https://download.gnome.org/sources/pygobject/3.36/pygobject-3.36.1.tar.xz
      tar -xf pygobject-3.36.1.tar.xz
      export PYGOBJECT_WITHOUT_PYCAIRO="1"
      echo 'PYGOBJECT_WITHOUT_PYCAIRO="1"' >> venv/bin/activate
      echo "export PYGOBJECT_WITHOUT_PYCAIRO" >> venv/bin/activate
      cd pygobject-3.36.1/
      ./../venv/bin/python3 setup.py build
      ./../venv/bin/python3 setup.py install
      cd ..
      venv/bin/python3 -m pip install six
      wget https://github.com/protocolbuffers/protobuf/releases/download/v3.9.0/protobuf-python-3.9.0.tar.gz
      tar -xzvf protobuf-python-3.9.0.tar.gz
      cd protobuf-python-3.9.0
      ./configure
      make
      make install
      ldconfig
      cd python
      ./../../venv/bin/python3 setup.py build --cpp_implementation
      ./../../venv/bin/python3 setup.py install --cpp_implementation
      cd ../..
      venv/bin/python3 -m pip install wheel
      venv/bin/python3 -m pip install wirepas-gateway
      find venv -type d -name __pycache__ -print0 | xargs -0 rm -rf
      cp -r venv/* ${SNAPCRAFT_PART_INSTALL}
    build-packages:
      - autoconf
      - automake
      - libtool
      - curl
      - g++
      - wget
      - python3.7
      - python3.7-venv
      - python3.7-distutils
      - build-essential
      - gcc
      - libffi-dev
      - libssl-dev
      - make
      - software-properties-common
      - libsystemd-dev
      - python3.7-dev
      - pkg-config
      - libglib2.0-dev
      - libgirepository1.0-dev


layout:
  /usr/lib/girepository-1.0:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0
  /usr/lib/gio:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gio
    

slots:
  wirepas-sink-0:
    interface: dbus
    bus: system
    name: com.wirepas.sink.sink0
plugs:
  wirepas-dbus-0:
    interface: dbus
    bus: system
    name: com.wirepas.sink.sink0
