#!/bin/sh -e

#Get the path for the serial port that is requested to be disconnected
sPath="$(snapctl get --slot :serial-port path)"


# Read list of sinks in use (0-9 are possible), to determine which one this plug was for
INPUT=$SNAP_DATA/sinkList.csv
OLDIFS=$IFS
IFS=','
[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 99; }
while read sinkID sinkBaud sinkPath sinkRstPin sinkRstPol sinkPlugged sinkActive
do
  if [[ "$sinkPath" == "$sPath" ]]; then
    #Disable the sink service associated with this plug
    snapctl stop sinkService${sinkID} --disable
    echo "Sink service ${sinkID} disabled due to disconnecting plug."
    exit 0
  fi
done < $INPUT
IFS=$OLDIFS

echo "No sink service recorded to be associated with this plug, please shut any associated sink services down manually."
